### PR TITLE
Add some params:

### PR DESCRIPTION
**Pull request by bigbigbang**
server params :
- dns proxy
- log file
- max log size
- obey pam restrictions
- panic action
- passdb backend
- passwd chat
- passwd program
- server role
- syslog
- usershare allow guests
share params :
- hosts allow
- acl allow execute always

Add a test on ubuntu 16.04

### CODE REVIEW

**Comment by bschonec** [comment]
Would be nice to merge this in.  Is this project active any longer?

**Comment by bigbigbang** [comment]
I don't know, my PR is pending since a long time now..
If no news, maybe someone can adopt this project ?

**Comment by ajjahn** [comment]
@bschonec @bigbigbang Unfortunately, I really only get a chance to maintain my puppet modules in spirts of free time. I wouldn't call the project inactive, just not as active as it ought to be. I went ahead and merged this. I'll try to find some time to work through the PRs and see if I can get another release out shortly.

**Comment by bigbigbang** [comment]
thanks :)
Good to read that you are still here :P

**Pull request merged**
