### PR TITLE
Add parameter to disable automatic join of domain

### PR DESCRIPTION
**Pull request by toelke**
I do not like having a Admin-Password lying around on my machine; since I use this module for a machine that will seldom be reinstalled, it's OK if the join needs an ssh-login.

### CODE REVIEW

**Comment by ajjahn** [comment]
Can you add specs for this?

**Comment by ajjahn** [comment]
Hmm, specs are passing for me. Are you testing against upstream master or your PR branch?

**Comment by toelke** [comment]
Both. I am now developing the spec by only testing "classes".

**Comment by ajjahn** [comment]
Build failed on Puppet 3.5.1/Ruby 1.8.7 due to json_pure >= 2.0.0. I pinned the version. Everything looks good now. Thanks!

**Comment by toelke** [comment]
Great, Thanks!

**Pull request merged**
