### PR TITLE
Adding the option for setting root preexec on a share

### PR DESCRIPTION
**Pull request by rendhalver**
Add option to set root preexec on a share.
I noticed you don;t have any spec tests for the share define yet do you plan on adding them or would you like a hand to add them?

### CODE REVIEW

**Comment by ajjahn** [comment]
> I've been a bit behind on issues and PRs, it would be a lot easier to merge this if it included specs. Would you be able to add them?

**Comment by rendhalver** [comment]
Sure. I would need to add them for the whole define.
I will try and get that sorted out soon.
I will add them to this PR and when we get that merged I will extend the tests for the other PRs.

**Comment by ajjahn** [comment]
@rendhalver Thanks! I'll likely release a new version once these are in.

(Sorry to spam you with a comment on all the issues.)

**Comment by rendhalver** [comment]
Totally understandable. I did spam you with PRs. :)

**Comment by rendhalver** [comment]
Hi again,
I am having some trouble getting the augeas changes tested.
The main issue is each change is actually an array of 20+ changes for every setting so each test seems like it will need to check each one of those changes.
This is what the tests output looks like on my local machine. https://travis-ci.org/ajjahn/puppet-samba/jobs/142472449 
It also looks like those tests produce entirely different results under ruby 1.8.7. https://travis-ci.org/ajjahn/puppet-samba/jobs/142472434

Any thoughts on how you want to proceed?
I found this that might help but it might also require a lot of configuring to get it setup: https://github.com/domcleal/rspec-puppet-augeas


I find augeas rather cumbersome for managing an ini file.
Are you set on using augeas for managing the smb.cnf file?
I have used [puppetlabs-inifile](https://forge.puppet.com/puppetlabs/inifile) for managing similar files and it works rather well. Augeas It seems to have the same basic idea as inifile.

[code example here](https://github.com/abstractitptyltd/abstractit-puppet/blob/production/manifests/config.pp#L31-L38)
The corresponding tests for that code is [here](https://github.com/abstractitptyltd/abstractit-puppet/blob/production/spec/classes/puppet_config_spec.rb#L46-L54).

I haven't used it in conjunction with augeas so I am not sure if they will work together.
I would have to have a play and see if it's possible.

**Comment by ajjahn** [comment]
Yes, I see. I think rspec-puppet-augeas could be useful. It would be nice to be able to test just a single change, ignoring all the other ones. I'm not married to using augeas, but I'm not sure depending on puppetlabs-inifile is my favorite choice either. I'd rather add testing dependancies than runtime dependancies. 

Since you've managed to get the tests passing by including the full set of changes in each spec, it might be easiest to just add a helper method to return the default set of changes allowing a single change to be overridden.

**Comment by rendhalver** [comment]
Yes I did get them working locally but hadn't noticed the checks passed for all of the test matrix.

A helper method does sound like the best idea considering I have 8 extra options to add as well.
I am not sure how to make one of those but I can work it out.

On  side note I added puppet-rspec-facts so I could get a decent set of base facts populated for the define and so it wasn't using my local facts.

**Comment by rendhalver** [comment]
I had a look around for how to create a helper method but I am still not sure how to do that.
Do you have any suggestions?

**Comment by rendhalver** [comment]
I believe my last commit adds tests for the rest of the current options to the samba::server::share define.
I also added a coverage report to show how much of the module is covered by the tests.

**Comment by ajjahn** [comment]
@rendhalver Wow, thanks for doing all of that! I'm going to merge this and now that we have some coverage we can look at merging your other PRs. 

As far as the helper method goes, I think a simple method that merges a hash of the default set of changes with a hash of targeted changes would be sufficient. I will see what I can whip up.

**Comment by rendhalver** [comment]
Awesome! I will make a start on the other ones soon.

**Comment by ajjahn** [comment]
Have a look at f0095397fd8a61367d39ae76bf63fb1c48885bbc. I pulled out the duplication, so adding additional specs should be a bit less verbose.

Also, I managed to break the build for 1.8.7 in doing so. I'll try and fix that in a bit.

**Comment by rendhalver** [comment]
That is definitely a lot cleaner. :)
I need to learn way more ruby to understand how that works.

**Pull request merged**
